---
fixtures:
  repositories:
    iptables: https://github.com/simp/pupmod-simp-iptables
    simpcat: https://github.com/simp/pupmod-simp-simpcat
    simplib: https://github.com/simp/pupmod-simp-simplib
    stdlib: https://github.com/simp/puppetlabs-stdlib
    tcpwrappers: https://github.com/simp/pupmod-simp-tcpwrappers
  symlinks:
    xinetd: "#{source_dir}"
